[package]
name = "fasta_cleaner"
version = "0.1.0"
authors = ["mohsen"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bio = "*"

[[bin]]
name = "fasta_cleaner"
path = "main.rs"
